### ISSUE TITLE
Index creation is missing :)

### ISSUE THREAD

**Issue by EmanuelaBoros** [EMBEDDIA/news_background_linking#1]

**Comment by EmanuelaBoros** [comment]
@creat89, would you mind adding the creation of the index script?

**Comment by creat89** [comment]
Which scripts are missing for indexing besides these: https://github.com/EMBEDDIA/news_background_linking/tree/main/Indexing_Scripts ?

**Comment by EmanuelaBoros** [comment]
the creation of the index structure (https://opster.com/guides/elasticsearch/glossary/elasticsearch-index/)

**Comment by creat89** [comment]
Hello Ema,

I've uploaded the file `settings.json` which should contain the requested information:
https://github.com/EMBEDDIA/news_background_linking/blob/main/Indexing_Scripts/settings.json

**Comment by EmanuelaBoros** [comment]
Thank you!
